# Generated by Django 2.2.20 on 2021-05-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='servicearea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_interests', to='users.ServiceArea'),
        ),
    ]
