# Generated by Django 2.2.20 on 2021-04-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210428_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cc_expiry',
            field=models.DateTimeField(),
        ),
    ]
