# Generated by Django 2.2.20 on 2021-04-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210428_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit_card',
        ),
    ]
