# Generated by Django 2.2.20 on 2021-04-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_credit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='servicearea',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='user_interests', to='users.ServiceArea'),
            preserve_default=False,
        ),
    ]
